In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from keras.activations import relu, sigmoid
from keras.utils import to_categorical
import pandas as pd
import numpy as np

Using TensorFlow backend.


In [34]:
dataset = pd.read_csv('data/train.csv')

In [35]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [36]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [37]:
dataset.drop(['Age'], axis = 1, inplace = True)
dataset.drop(['Cabin'], axis = 1, inplace = True)
dataset.drop(['Embarked'], axis = 1, inplace = True)
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                             Heikkinen, Miss. Laina  female      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                           Allen, Mr. William Henry    male      0      0   

             Ticket     Fare  
0         A/5 21171   7.2500  
1          PC 17599  71.2833  
2  STON/O2. 3101282   7.9250  
3            113803  53.1000  
4            373450   8.0500

In [38]:
dataset.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
SibSp          0
Parch          0
Ticket         0
Fare           0
dtype: int64

# through getdummies

In [39]:
sex = pd.get_dummies(dataset['Sex'])
sex.head()

female  male
0     0.0   1.0
1     1.0   0.0
2     1.0   0.0
3     1.0   0.0
4     0.0   1.0

In [40]:
dataset.drop(['Sex'], axis = 1, inplace = True)
dataset.drop(['Name'], axis = 1, inplace = True)
dataset.drop(['Ticket'], axis = 1, inplace = True)
dataset.head()

PassengerId  Survived  Pclass  SibSp  Parch     Fare
0            1         0       3      1      0   7.2500
1            2         1       1      1      0  71.2833
2            3         1       3      0      0   7.9250
3            4         1       1      1      0  53.1000
4            5         0       3      0      0   8.0500

In [41]:
dataset = pd.concat([dataset, sex], axis = 1)
dataset.head()

PassengerId  Survived  Pclass  SibSp  Parch     Fare  female  male
0            1         0       3      1      0   7.2500     0.0   1.0
1            2         1       1      1      0  71.2833     1.0   0.0
2            3         1       3      0      0   7.9250     1.0   0.0
3            4         1       1      1      0  53.1000     1.0   0.0
4            5         0       3      0      0   8.0500     0.0   1.0

In [42]:
X = dataset.iloc[:, :7].values
y = dataset.iloc[:, 1].values

In [43]:
X

array([[   1.    ,    0.    ,    3.    , ...,    0.    ,    7.25  ,    0.    ],
       [   2.    ,    1.    ,    1.    , ...,    0.    ,   71.2833,    1.    ],
       [   3.    ,    1.    ,    3.    , ...,    0.    ,    7.925 ,    1.    ],
       ..., 
       [ 889.    ,    0.    ,    3.    , ...,    2.    ,   23.45  ,    1.    ],
       [ 890.    ,    1.    ,    1.    , ...,    0.    ,   30.    ,    0.    ],
       [ 891.    ,    0.    ,    3.    , ...,    0.    ,    7.75  ,    0.    ]])

In [44]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1,

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size = 0.05, random_state = 0)

In [89]:
model = Sequential()
model.add(Dense(12, input_dim=7, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [90]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# accuracy varies alternatively

In [92]:
model.fit(X_train, y_train, epochs = 10, batch_size = 64, validation_data = [X_valid, y_valid])

Train on 846 samples, validate on 45 samples
Epoch 1/10
846/846 [==============================] - 0s 71us/step - loss: 5.8463 - acc: 0.6194 - val_loss: 6.6773 - val_acc: 0.5556
Epoch 2/10
846/846 [==============================] - 0s 76us/step - loss: 5.7482 - acc: 0.6170 - val_loss: 6.5529 - val_acc: 0.5556
Epoch 3/10
846/846 [==============================] - 0s 125us/step - loss: 5.2385 - acc: 0.5780 - val_loss: 8.5611 - val_acc: 0.4444
Epoch 4/10
846/846 [==============================] - 0s 86us/step - loss: 8.8027 - acc: 0.3995 - val_loss: 8.5689 - val_acc: 0.4444
Epoch 5/10
846/846 [==============================] - 0s 98us/step - loss: 6.2829 - acc: 0.4291 - val_loss: 8.5727 - val_acc: 0.4444
Epoch 6/10
846/846 [==============================] - 0s 89us/step - loss: 6.4417 - acc: 0.5461 - val_loss: 7.1636 - val_acc: 0.5556
Epoch 7/10
846/846 [==============================] - 0s 90us/step - loss: 6.1348 - acc: 0.6194 - val_loss: 7.1636 - val_acc: 0.5556
Epoch 8/10
846/846 [===

# through label encoding

In [105]:
dataset = pd.read_csv('data/train.csv')

In [106]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [107]:
dataset.drop(['Name'], axis = 1, inplace = True)
dataset.drop(['Ticket'], axis = 1, inplace = True)
dataset.drop(['Age'], axis = 1, inplace = True)
dataset.drop(['Cabin'], axis = 1, inplace = True)
dataset.drop(['Embarked'], axis = 1, inplace = True)
dataset.head()

PassengerId  Survived  Pclass     Sex  SibSp  Parch     Fare
0            1         0       3    male      1      0   7.2500
1            2         1       1  female      1      0  71.2833
2            3         1       3  female      0      0   7.9250
3            4         1       1  female      1      0  53.1000
4            5         0       3    male      0      0   8.0500

In [198]:
A = dataset.iloc[:, :7].values
b = dataset.iloc[:, 3].values

In [199]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [200]:
sex_label_encoding = LabelEncoder()

In [201]:
b[:, ] = sex_label_encoding.fit_transform(b[:, ])   #didnt understand

In [202]:
b

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0,

In [218]:
from sklearn.model_selection import train_test_split
A_train, A_valid, b_train, b_valid = train_test_split(A, b, test_size = 0.05, random_state = 0)

In [219]:
model = Sequential()
model.add(Dense(12, input_dim=7, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [220]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# accuracy varies alternatively

In [221]:
model.fit(A_train, b_train, epochs = 10, batch_size =64 , validation_data = [A_valid, b_valid])

Train on 846 samples, validate on 45 samples
Epoch 1/10
846/846 [==============================] - 3s 3ms/step - loss: 5.7026 - acc: 0.6277 - val_loss: 6.0227 - val_acc: 0.6222
Epoch 2/10
846/846 [==============================] - 0s 83us/step - loss: 5.5796 - acc: 0.6489 - val_loss: 6.0227 - val_acc: 0.6222
Epoch 3/10
846/846 [==============================] - 0s 89us/step - loss: 5.5790 - acc: 0.6489 - val_loss: 6.0227 - val_acc: 0.6222
Epoch 4/10
846/846 [==============================] - 0s 102us/step - loss: 5.5785 - acc: 0.6489 - val_loss: 6.0227 - val_acc: 0.6222
Epoch 5/10
846/846 [==============================] - 0s 98us/step - loss: 5.5770 - acc: 0.6489 - val_loss: 6.0073 - val_acc: 0.6222
Epoch 6/10
846/846 [==============================] - 0s 90us/step - loss: 5.5761 - acc: 0.6489 - val_loss: 5.9983 - val_acc: 0.6222
Epoch 7/10
846/846 [==============================] - 0s 91us/step - loss: 5.5750 - acc: 0.6489 - val_loss: 5.9869 - val_acc: 0.6222
Epoch 8/10
846/846 [====

# OneHotEncoding

In [242]:
sex_onehot_encoder = OneHotEncoder(categorical_features = [2], dtype = np.int)
b = sex_onehot_encoder.fit_transform(X).toarray()

In [243]:
from sklearn.model_selection import train_test_split
A_train, A_valid, b_train, b_valid = train_test_split(A, b, test_size = 0.05, random_state = 0)

In [244]:
model = Sequential()
model.add(Dense(12, input_dim=7, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [245]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# accuracy varies alternatively

In [246]:
model.fit(X_train, y_train, epochs = 10, batch_size =64 , validation_data = [X_valid, y_valid])

Train on 846 samples, validate on 45 samples
Epoch 1/10
846/846 [==============================] - 3s 4ms/step - loss: 6.6841 - acc: 0.5626 - val_loss: 7.1276 - val_acc: 0.5556
Epoch 2/10
846/846 [==============================] - 0s 85us/step - loss: 6.0219 - acc: 0.6194 - val_loss: 7.0431 - val_acc: 0.5556
Epoch 3/10
846/846 [==============================] - 0s 87us/step - loss: 5.9975 - acc: 0.6194 - val_loss: 6.9788 - val_acc: 0.5556
Epoch 4/10
846/846 [==============================] - 0s 104us/step - loss: 5.9588 - acc: 0.6194 - val_loss: 6.7152 - val_acc: 0.5778
Epoch 5/10
846/846 [==============================] - 0s 91us/step - loss: 8.3070 - acc: 0.4598 - val_loss: 8.7079 - val_acc: 0.4444
Epoch 6/10
846/846 [==============================] - 0s 92us/step - loss: 9.7938 - acc: 0.3806 - val_loss: 8.6802 - val_acc: 0.4444
Epoch 7/10
846/846 [==============================] - 0s 83us/step - loss: 9.7660 - acc: 0.3806 - val_loss: 8.6378 - val_acc: 0.4444
Epoch 8/10
846/846 [====